### ISSUE TITLE
If mal creado

### ISSUE THREAD

**Issue by gaal1le0** [fjrf16/Exercises-JS-I-#1]
https://github.com/fjrf16/Exercises-JS-I-/blob/ff5397bd113c428bd1461712d035a6f3a975698a/assets/index.js#L37

Si te fijas en tu código tienes una sentencia que en caso de ser cierta no haría nada, eso es desperdiciar recursos a lo bestia, para tu problema deberas pensar en un solo if que valide una condición, olvidate del else.
Te dejo a ti pensar como podrías solucionarlo.

**Comment by fjrf16** [comment]
He solucionado el if mal creado poniéndolo así:
```
if (typeof array[index] !== 'string' && typeof array[index] !== 'number'){
      // elimina el valor del array ya que no cumple los requisitos
      array.splice(index,1);
```
