### ISSUE TITLE
Mal concepto y fallo en optimización

### ISSUE THREAD

**Issue by gaal1le0** [fjrf16/Exercises-JS-I-#2]
https://github.com/fjrf16/Exercises-JS-I-/blob/ff5397bd113c428bd1461712d035a6f3a975698a/assets/index.js#L56

Esto que me has propuesto para solucionarme el problema es un algoritmo super costoso, que tira demasiados recursos, debes optimizarlo y buscar una solución mas acorde al problema. Estás matando moscas a cañonazos. 
Además me hablas de recursividad, pero ninguna de las funciones que usas como auxiliares de la que estoy señalandote es recursiva. Una funcion es recursiva cuando se llama así misma dentro.

Debes buscar una solución más optima para el problema y presentarmela.

**Comment by fjrf16** [comment]
Recursividad como ya te comenté me lié y quería decir dinámica  jajaja, lo he modificado por una función que lo hace de forma más simple y muchas menos líneas de código.
