### ISSUE TITLE
Solución poco optima

### ISSUE THREAD

**Issue by gaal1le0** [fjrf16/Exercises-JS-I-#4]
https://github.com/fjrf16/Exercises-JS-I-/blob/ff5397bd113c428bd1461712d035a6f3a975698a/assets/index.js#L114

Esto que me has propuesto para solucionarme el problema es un algoritmo super costoso, que tira demasiados recursos, debes optimizarlo y buscar una solución mas acorde al problema. 

Debes buscar una solución más optima para el problema y presentarmela.

Te recomiendo borrarlo todo y comenzar del principio!!
PD: Aprenderás mas y te darás cuenta del error

**Comment by fjrf16** [comment]
He encontrado la forma de hacerlo con set, lo he dejado así:
```
function NoRepeat(array1) {

// primero limpiamos los arrays y dejamos con strings
  let Array=cleanArray(array1);
 
  let withoutReps = new Set(Array);
  
  const arrayWithoutRep = [...withoutReps];
  console.log(arrayWithoutRep)
  return arrayWithoutRep;
}
```
