### ISSUE TITLE
El formato del código es raro

### ISSUE THREAD

**Issue by gaal1le0** [fjrf16/Exercises-JS-I-#5]
https://github.com/fjrf16/Exercises-JS-I-/blob/52b46e27408ad256b20edc528b44f530597f33c4/assets/index.js#L1.

El código no se ve elegante, para que quede bonito y precioso, es decir perfecto (cómo a mi me gusta) tienes que seleccionar todo el código, hacer click derecho y darle al botón que pone format document. 
Formatea el documento y reenvíame la tarea a través de BreathCode.

**Comment by fjrf16** [comment]
He formateado para que quede precioso jaja lo vuelvo a subir
